[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
curve25519-dalek = { version = "4.0",features = ["rand_core","serde"] }

crypto = { path = "../crypto" }
thiserror = "2.0.12"
serde_json = "1.0.140"